import { Artwork } from '../interfaces/artwork.interface';

export const ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Forest Spirit',
    category: 'illustration',
    description: 'A digital illustration exploring nature and mysticism.',
    tags: ['nature', 'character', 'digital'],
    src: 'assets/images/artworks/forest-spirit.jpg',
    thumbnail: 'assets/images/thumbnails/forest-spirit.webp',
    featured: true,
    year: 2024,
  },
  {
    id: '2',
    title: 'Urban Bloom',
    category: 'illustration',
    description: 'City life meets organic forms in this mixed-media piece.',
    tags: ['urban', 'abstract', 'color'],
    src: 'assets/images/artworks/urban-bloom.jpg',
    thumbnail: 'assets/images/thumbnails/urban-bloom.webp',
    featured: true,
    year: 2024,
  },
  {
    id: '3',
    title: 'Solaris Brand',
    category: 'branding',
    description: 'Full brand identity for a sustainable energy startup.',
    tags: ['branding', 'logo', 'identity'],
    src: 'assets/images/artworks/solaris.jpg',
    thumbnail: 'assets/images/thumbnails/solaris.webp',
    featured: true,
    year: 2023,
  },
  {
    id: '4',
    title: 'Night Market',
    category: 'illustration',
    description: 'A vibrant scene inspired by Southeast Asian night markets.',
    tags: ['scene', 'color', 'detailed'],
    src: 'assets/images/artworks/night-market.jpg',
    thumbnail: 'assets/images/thumbnails/night-market.webp',
    featured: false,
    year: 2023,
  },
  {
    id: '5',
    title: 'Echo UI Kit',
    category: 'ui',
    description: 'A minimal dark-mode UI component kit designed in Figma.',
    tags: ['figma', 'ui', 'components'],
    src: 'assets/images/artworks/echo-ui.jpg',
    thumbnail: 'assets/images/thumbnails/echo-ui.webp',
    featured: false,
    year: 2024,
  },
];
